name: hotel-booking-env

channels:
  - conda-forge

dependencies:
  - python=3.10
  - pip
  - pip:
      - pandas
      - dagshub
      - numpy
      - mlflow
      - scikit-learn
      - matplotlib
      - seaborn
      - kagglehub
