# -*- coding: utf-8 -*-
"""modelling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17uordG2-H7OAKvOYHikeV-y2TQFDIKV-
"""

import pandas as pd
import kagglehub
import os
import mlflow
import mlflow.sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score
from sklearn.impute import SimpleImputer


def main():
    # 1. Download Dataset
    path = kagglehub.dataset_download("jessemostipak/hotel-booking-demand")
    csv_path = os.path.join(path, "hotel_bookings.csv")
    df = pd.read_csv(csv_path)

    # 2. Preprocessing Ringan
    df = df.drop_duplicates()
    df["children"] = df["children"].fillna(0)
    df["agent"] = df["agent"].fillna(0)
    df["company"] = df["company"].fillna(0)

    X = df.drop(columns=["is_canceled"])
    y = df["is_canceled"]

    imputer = SimpleImputer(strategy="median")
    X = pd.DataFrame(imputer.fit_transform(X), columns=X.columns)

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    # 3. Training + MLflow
    with mlflow.start_run():
        model = RandomForestClassifier(
            n_estimators=200,
            max_depth=20,
            random_state=42,
            n_jobs=-1
        )
        model.fit(X_train, y_train)

        y_pred = model.predict(X_test)

        acc = accuracy_score(y_test, y_pred)
        f1 = f1_score(y_test, y_pred)

        mlflow.log_metric("accuracy", acc)
        mlflow.log_metric("f1_score", f1)

        mlflow.sklearn.log_model(model, "model")

        print(f"Training selesai | accuracy={acc:.4f}, f1={f1:.4f}")


if __name__ == "__main__":
    main()